"""
Django settings for mainsite project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cl*f&v-)*(35k8zkq-5klv0zd4&ro(_cpm^tg+vagkp16nb$al'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['157.245.82.143', '*']

SITE_ID = 1

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map'],
    }
}

X_FRAME_OPTIONS = 'SAMEORIGIN'

THUMBNAIL_DEBUG = True

# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'djangocms_text_ckeditor',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'easy_thumbnails',
    'filer',
    'mptt',
    'djangocms_link',
    'webpack_loader',
    'import_export',
    'mainsite',
    'bannerapp',
    'genericapp',
    'formapp',
    'faqapp',
    'productapp',
]

MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'mainsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'mainsite', 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'django.template.context_processors.static',
            ],
            'libraries':{
                'product_detail': 'productapp.templatetags.product_detail',
                'product_image': 'productapp.templatetags.product_image',
                'product_filters': 'productapp.templatetags.product_filters',
            },
        },
    },
]

CMS_TEMPLATES = [
    ('index.html', 'Template base'),
]

CMS_PLACEHOLDER_CONF = {
    None: {
        'excluded_plugins': [
            'LinkPlugin',
            'TextPlugin',
            'SnippetPlugin',
            #'SeoSinglePagePlugin1',
            #'SeoBlogPagePlugin2',
        ],
        # 'default_plugins': [{
        #     'plugin_type': 'CenterTextPlugin',
        #     'values': {
        #         'full_text': '<p>L...</p>',
        #     },
        # }],
    },
    'category-menu': {
        'default_plugins': [{
            'plugin_type': 'ProductCategoryPlugin2',
            'values': {},
        }],
        'plugins': [
            'ProductCategoryPlugin2',
        ],
        'name': "Filters",
    },
    'product-list': {
        'default_plugins': [{
            'plugin_type': 'ProductGridPlugin1',
            'values': {
                #'fild-name': value,
            },
        }],
        'plugins': [
            'ProductGridPlugin1',
        ],
        'name': "Products",
    }
}

WSGI_APPLICATION = 'mainsite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'project.db'),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

LANGUAGES = [
    ('pt-br', 'Português'),
    ('en', 'English'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'mainsite', 'static'),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# COLOR OPTIONS FOR FILTERS
PRODUCSTS_COLORS_HEXADECIMAL = (
    ('Branco', '#FFFFFF'),
    ('Euforia', '#55CFC4'),
    ('Marinho', '#120A8F'),
    ('Orange Fresh', '#FFA500'),
    ('Preto', '#000000'),
    ('Preto com Rosa Pink', '#F653A9/#000000'), # Para duas cores
    ('Rosa', '#FDACBA'),
    ('Rosa Pink', '#F653A9'),
    ('Scarlet', '#BB0622'),
    ('Laranja', '#FFA500'),
    ('Amarelo', '#FFD200'),
)

# PRINTS OPTIONS FOR FILTERS
PRODUCSTS_PRINTS_IMAGES = (
    ('Abstrata', 'estampa_1.jpg'),
    ('Alicia', 'estampa_2.jpg'),
    ('Amarelo', 'estampa_3.jpg'),
    ('Berenice', 'estampa_1.jpg'),
    ('Elisa', 'estampa_2.jpg'),
    ('Floral', 'estampa_3.jpg'),
    ('Floral Acqua', 'estampa_1.jpg'),
    ('Folha Tropical', 'estampa_2.jpg'),
    ('Folhagens', 'estampa_3.jpg'),
    ('Folhas', 'estampa_1.jpg'),
    ('Helen', 'estampa_2.jpg'),
    ('Listras', 'estampa_3.jpg'),
    ('Mandala', 'estampa_1.jpg'),
    ('Manoela', 'estampa_2.jpg'),
    ('Maya', 'estampa_3.jpg'),
    ('Olho Grego', 'estampa_1.jpg'),
    ('Onça', 'estampa_2.jpg'),
    ('Outuno', 'estampa_3.jpg'),
    ('Poá', 'estampa_1.jpg'),
    ('Tigre', 'estampa_2.jpg'),
    ('Tropical', 'estampa_3.jpg'),
    ('Virginia', 'estampa_1.jpg'),
    ('Zebra', 'estampa_2.jpg'),
    ('Zebra Nude e Rosa', 'estampa_3.jpg'),
)
# END - DEFAULTS SETTINGS

