# Generated by Django 3.2.20 on 2023-08-02 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20230723_2308'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('bannerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPlugin4',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bannerapp_bannerplugin4', serialize=False, to='cms.cmsplugin')),
                ('first_title', models.CharField(default='', help_text='Insira o título.', max_length=150, verbose_name='Título do bloco princiapal')),
                ('first_subtitle', djangocms_text_ckeditor.fields.HTMLField(default='', max_length=1500, verbose_name='Subtítulo do bloco princiapal')),
                ('b4_first_image_size', models.CharField(default='1020x880', editable=False, max_length=100)),
                ('first_text_alt', models.CharField(help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem do bloco principal')),
                ('second_title', models.CharField(default='', help_text='Insira o título.', max_length=150, verbose_name='Título do segundo bloco')),
                ('second_subtitle', djangocms_text_ckeditor.fields.HTMLField(default='', max_length=1500, verbose_name='Subtítulo do segundo bloco')),
                ('b4_second_image_size', models.CharField(default='1020x880', editable=False, max_length=100)),
                ('second_text_alt', models.CharField(help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem do segundo bloco')),
                ('third_title', models.CharField(default='', help_text='Insira o título.', max_length=150, verbose_name='Título do terceiro bloco')),
                ('third_subtitle', djangocms_text_ckeditor.fields.HTMLField(default='', max_length=1500, verbose_name='Subtítulo do terceiro bloco')),
                ('b4_third_image_size', models.CharField(default='1020x880', editable=False, max_length=100)),
                ('third_text_alt', models.CharField(help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem do terceiro bloco')),
                ('fourth_title', models.CharField(default='', help_text='Insira o título.', max_length=150, verbose_name='Título do quarto bloco')),
                ('fourth_subtitle', djangocms_text_ckeditor.fields.HTMLField(default='', max_length=1500, verbose_name='Subtítulo do quarto bloco')),
                ('b4_fourth_image_size', models.CharField(default='1020x880', editable=False, max_length=100)),
                ('fourth_text_alt', models.CharField(help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem do quarto bloco')),
                ('fifth_title', models.CharField(default='', help_text='Insira o título.', max_length=150, verbose_name='Título do quinto bloco')),
                ('fifth_subtitle', djangocms_text_ckeditor.fields.HTMLField(default='', max_length=1500, verbose_name='Subtítulo do quinto bloco')),
                ('b4_fifth_image_size', models.CharField(default='1020x880', editable=False, max_length=100)),
                ('fifth_text_alt', models.CharField(help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem do quinto bloco')),
                ('b4_fifth_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 1020x880', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b4_fifth_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem a esquerda')),
                ('b4_first_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 1020x880', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b4_first_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem a esquerda')),
                ('b4_fourth_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 1020x880', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b4_fourth_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem a esquerda')),
                ('b4_second_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 1020x880', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b4_second_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem a esquerda')),
                ('b4_third_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 1020x880', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b4_third_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem a esquerda')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
