# Generated by Django 3.2.20 on 2023-08-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerapp', '0002_bannerplugin4'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerplugin4',
            name='image_filter_color',
            field=models.CharField(choices=[('dark-filter', 'Filtro Escuro'), ('withe-filter', 'Filtro Claro')], default='dark-filter', help_text='Selecione o tipo de filtro das imagens', max_length=30, verbose_name='Usar somente a opção'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='text_color',
            field=models.CharField(choices=[('text-dark-pink-belamarca', 'Rosa Escuro'), ('text-pink-belamarca', 'Rosa Claro'), ('text-blue-belamarca', 'Azul'), ('text-orange-belamarca', 'Laranja'), ('text-yellow-belamarca', 'Amarelo'), ('text-dark-text-belamarca', 'Preto'), ('text-light-text-belamarca', 'Branco')], default='text-light-text-belamarca', help_text='Selecione a cor dos textos', max_length=30, verbose_name='Somente os textos da capa'),
        ),
        migrations.AlterField(
            model_name='bannerplugin4',
            name='first_title',
            field=models.CharField(default='', help_text='Insira o título.', max_length=150, verbose_name='Título do bloco principal'),
        ),
    ]
