# Generated by Django 3.2.20 on 2023-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerapp', '0003_auto_20230817_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerplugin4',
            name='fifth_button_text',
            field=models.CharField(default='Acesse Agora!', help_text='Insira o texto do botão.', max_length=100, verbose_name='Texto do botão do quinto bloco'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='fifth_button_url',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link para o botão do quinto bloco'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='first_button_text',
            field=models.CharField(default='Acesse Agora!', help_text='Insira o texto do botão.', max_length=100, verbose_name='Texto do botão do bloco princiapal'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='first_button_url',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link para o botão do bloco princiapal'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='fourth_button_text',
            field=models.CharField(default='Acesse Agora!', help_text='Insira o texto do botão.', max_length=100, verbose_name='Texto do botão do quarto bloco'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='fourth_button_url',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link para o botão do quarto bloco'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='second_button_text',
            field=models.CharField(default='Acesse Agora!', help_text='Insira o texto do botão.', max_length=100, verbose_name='Texto do botão do segundo bloco'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='second_button_url',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link para o botão do segundo bloco'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='third_button_text',
            field=models.CharField(default='Acesse Agora!', help_text='Insira o texto do botão.', max_length=100, verbose_name='Texto do botão do terceiro bloco'),
        ),
        migrations.AddField(
            model_name='bannerplugin4',
            name='third_button_url',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link para o botão do terceiro bloco'),
        ),
    ]
