# Generated by Django 3.2.20 on 2023-07-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20230722_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='last_atualization',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Última atualização'),
        ),
    ]
