# Generated by Django 3.2.20 on 2023-07-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='p2_image_image_resize',
            field=models.ImageField(blank=True, default='static/products/default.jpg', help_text='Enviar arquivos .png ou .jpg. Tamanho ideal 100x100.', null=True, upload_to='products_images/prints/', verbose_name='Imagem do atributo.'),
        ),
    ]
