# Generated by Django 3.2.20 on 2023-08-01 22:26

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0015_productcarrossel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcarrossel',
            options={'verbose_name': 'Carrossel de Produtos', 'verbose_name_plural': 'Carrossíes de Produtos'},
        ),
        migrations.AddField(
            model_name='productcarrossel',
            name='attribute_options',
            field=models.ManyToManyField(blank=True, related_name='products_to_carrossel_by_attribute_option', to='productapp.AttributeOption', verbose_name='Selecione as Opções de Atributos desejadas'),
        ),
        migrations.AddField(
            model_name='productcarrossel',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products_to_carrossel_by_attribute', to='productapp.Attribute', verbose_name='Selecione os Atributos desejadas'),
        ),
        migrations.AddField(
            model_name='productcarrossel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products_to_carrossel_by_category', to='productapp.Category', verbose_name='Selecione as Categorias desejadas'),
        ),
        migrations.AddField(
            model_name='productcarrossel',
            name='show_only',
            field=models.CharField(choices=[('category', 'Categoria'), ('subcategory', 'Subcategoria'), ('attribute', 'Atributo'), ('attribute_option', 'Opção de Atributo')], default='category', help_text='Selecione entre Categoria, Subcategoria, Atributo ou Opção de Atributo', max_length=16, verbose_name='Usar somente a opção'),
        ),
        migrations.AddField(
            model_name='productcarrossel',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products_to_carrossel_by_subcategory', to='productapp.Subcategory', verbose_name='Selecione as Subategorias desejadas'),
        ),
        migrations.AlterField(
            model_name='productcarrossel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_to_carrossel_by_product', to='productapp.Product'),
        ),
        migrations.AlterField(
            model_name='productcarrossel',
            name='subtitle',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text='Insira um subtítulo para o Carrossel', max_length=1000, null=True, verbose_name='Subtítulo do Carrossel'),
        ),
        migrations.AlterField(
            model_name='productcarrossel',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título do Carrossel'),
        ),
    ]
