# Generated by Django 3.2.20 on 2023-08-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0016_auto_20230801_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcarrossel',
            name='show_only',
            field=models.CharField(choices=[('category', 'Categoria'), ('subcategory', 'Subcategoria'), ('attribute', 'Atributo'), ('attribute_option', 'Opção de Atributo'), ('product', 'Produto')], default='category', help_text='Selecione entre Categoria, Subcategoria, Atributo ou Opção de Atributo', max_length=16, verbose_name='Usar somente a opção'),
        ),
    ]
