# Generated by Django 3.2.20 on 2023-08-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0017_alter_productcarrossel_show_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcarrossel',
            name='text_color',
            field=models.CharField(choices=[('text-dark-pink-belamarca', 'Rosa Escuro'), ('text-pink-belamarca', 'Rosa Claro'), ('text-blue-belamarca', 'Azul'), ('text-orange-belamarca', 'Laranja'), ('text-yellow-belamarca', 'Amarelo'), ('text-dark-text-belamarca', 'Preto'), ('text-light-text-belamarca', 'Branco')], default='text-blue-belamarca', help_text='Selecione a cor dos textos', max_length=30, verbose_name='Somente os textos da capa'),
        ),
    ]
