# Generated by Django 3.0.14 on 2022-06-01 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('termos', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='OccupationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pt', models.CharField(max_length=120, verbose_name='Nome da área em Português')),
                ('name_en', models.CharField(max_length=120, verbose_name='Nome da área em Inglês')),
                ('name_es', models.CharField(max_length=120, verbose_name='Nome da área em Espanhol')),
                ('responsible_name', models.CharField(default='', max_length=120, verbose_name='Nome do responsável pela área')),
                ('responsible_email', models.EmailField(default='', max_length=120, verbose_name='E-mail do responsável pela área')),
                ('disp', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=12, verbose_name='Disponibilidade')),
            ],
            options={
                'verbose_name': 'Área para o Trabalhe Conosco',
                'verbose_name_plural': 'Áreas para o Trabalhe Conosco',
            },
        ),
        migrations.CreateModel(
            name='WorkWithUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('area', models.CharField(max_length=20, verbose_name='Área')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('message', models.TextField(max_length=100, verbose_name='Mensagem')),
                ('curriculo', models.FileField(upload_to='curriculos/% Y/% m/% d/', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Trabalhe Conosco',
                'verbose_name_plural': 'Trabalhe Conosco',
            },
        ),
        migrations.CreateModel(
            name='FormWorkWithUsPlugin2',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='formapp_formworkwithusplugin2', serialize=False, to='cms.CMSPlugin')),
                ('f2_first_left_image_size', models.CharField(default='490x560', editable=False, max_length=100)),
                ('first_left_text_alt', models.CharField(help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('f2_second_left_image_size', models.CharField(default='345x289', max_length=100)),
                ('second_left_text_alt', models.CharField(help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('title', models.CharField(default='Trabalhe Conosco', help_text='Título para o formulário.', max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(default='Preencha o formulário abaixo', help_text='Subtítulo para o formulário.', max_length=100, verbose_name='Subtítulo')),
                ('f2_first_left_image_resize', filer.fields.image.FilerImageField(help_text='Tamanho ideal 490x560.', on_delete=django.db.models.deletion.PROTECT, related_name='f2_first_left_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem vertical a esquerda(tela computador).')),
                ('f2_second_left_image_resize', filer.fields.image.FilerImageField(help_text='Tamanho ideal 345x289.', on_delete=django.db.models.deletion.PROTECT, related_name='f2_second_left_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem quadrada no topo(tela tablet e celular)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
