# Generated by Django 3.0.14 on 2022-06-07 23:00

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-mail do responsável pelo assunto')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone')),
                ('subject', models.CharField(max_length=20, verbose_name='Assunto')),
                ('message', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do assunto')),
                ('responsible_name', models.CharField(default='', max_length=120, verbose_name='Nome do responsável pelo assunto')),
                ('responsible_email', models.EmailField(default='', max_length=120, verbose_name='E-mail do responsável pelo assunto')),
                ('disp', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=12, verbose_name='Disponibilidade')),
            ],
            options={
                'verbose_name': 'Assunto do formulário de Contato',
                'verbose_name_plural': 'Assuntos do formulário de Contato',
            },
        ),
        migrations.CreateModel(
            name='FormContactPlugin1',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='formapp_formcontactplugin1', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='Trabalhe Conosco', help_text='Título para o formulário.', max_length=100, verbose_name='Título')),
                ('address', djangocms_text_ckeditor.fields.HTMLField(default='Estrada Municipal Linha Ávila, Rua Linha Carazal, 501 Gramado/RS, 95670-000', help_text='Insira o endereço do parque.', max_length=500, verbose_name='Endereço')),
                ('phone', models.CharField(default='+55 54 3050-1700', help_text='Insira o telefone para contato.', max_length=100, verbose_name='Telefone')),
                ('email', models.EmailField(default='acquamotion@gramadoparks.com', help_text='Insira o e-mail para contato.', max_length=100, verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='formworkwithusplugin2',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='formworkwithusplugin2',
            name='f2_first_left_image_resize',
        ),
        migrations.RemoveField(
            model_name='formworkwithusplugin2',
            name='f2_second_left_image_resize',
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.DeleteModel(
            name='OccupationArea',
        ),
        migrations.DeleteModel(
            name='WorkWithUs',
        ),
        migrations.DeleteModel(
            name='FormWorkWithUsPlugin2',
        ),
    ]
