# Generated by Django 3.0.14 on 2022-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20220607_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
