# Generated by Django 3.0.14 on 2022-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_contact_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='Termos'),
        ),
    ]
