# Generated by Django 3.0.14 on 2022-08-27 21:26

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_auto_20220629_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcontactplugin1',
            name='address',
        ),
        migrations.RemoveField(
            model_name='formcontactplugin1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formcontactplugin1',
            name='phone',
        ),
        migrations.AddField(
            model_name='formcontactplugin1',
            name='subtitle',
            field=djangocms_text_ckeditor.fields.HTMLField(default='Preencha o formulário para receber um atendimento exclusivo da nossa equipe.', help_text='Subtítulo para o formulário.', max_length=500, verbose_name='Subtítulo'),
        ),
    ]
