# Generated by Django 3.0.14 on 2022-08-27 22:32

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_formnewsletterplugin2_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formnewsletterplugin2',
            name='subtitle',
            field=djangocms_text_ckeditor.fields.HTMLField(default='Inscreva-se na nossa newsletter para receber um cumpom de 30% off em qualquer produto.', help_text='Subtítulo para o formulário.', max_length=500, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='formnewsletterplugin2',
            name='title',
            field=models.CharField(default='Cumpom de 30% off para você', help_text='Título para o formulário.', max_length=100, verbose_name='Título'),
        ),
    ]
