# Generated by Django 3.0.14 on 2022-08-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_auto_20220827_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontactplugin1',
            name='title',
            field=models.CharField(default='Fale com a gente :)', help_text='Título para o formulário.', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='formnewsletterplugin2',
            name='title',
            field=models.CharField(default='Cupom de 30% off para você', help_text='Título para o formulário.', max_length=100, verbose_name='Título'),
        ),
    ]
