# Generated by Django 3.0.14 on 2022-08-27 22:37

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_auto_20220827_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formnewsletterplugin2',
            name='subtitle',
            field=djangocms_text_ckeditor.fields.HTMLField(default='Inscreva-se na nossa newsletter para receber um cumpom de 30% off em seu e-mail.', help_text='Subtítulo para o formulário.', max_length=500, verbose_name='Subtítulo'),
        ),
    ]
