# Generated by Django 3.0.14 on 2022-08-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_auto_20220827_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletter'},
        ),
    ]
