# Generated by Django 3.0.14 on 2022-06-10 20:32

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFaqPlugin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Digite uma pergunta.', max_length=250, verbose_name='Pergunta')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(default='', help_text='Digite uma resposta para a pergunta.', max_length=3000, verbose_name='Resposta')),
                ('disp', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=12, verbose_name='Disponibilidade')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
            },
        ),
        migrations.CreateModel(
            name='FaqPlugin1',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='faqapp_faqplugin1', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='', help_text='Digite um título para o bloco', max_length=200, verbose_name='Título do Perguntas Frequentes')),
                ('ordination', models.CharField(choices=[('new_to_old', 'Dos mais recentes para os mais antigos'), ('old_to_new', 'Dos mais antigos para os mais recentes'), ('random', 'Ordem aleatória')], default='old_to_new', max_length=12, verbose_name='Ordenação')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
