# Generated by Django 3.0.14 on 2022-06-10 20:59

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faqapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfaqplugin1',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', help_text='Digite uma resposta para a pergunta.', max_length=4000, verbose_name='Resposta'),
        ),
    ]
