# Generated by Django 3.0.14 on 2022-06-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqapp', '0002_auto_20220610_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqplugin1',
            name='title',
            field=models.CharField(default='Perguntas Frequentes', help_text='Digite um título para o bloco', max_length=200, verbose_name='Título do Perguntas Frequentes'),
        ),
    ]
