# Generated by Django 3.2.20 on 2023-07-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqapp', '0003_auto_20220610_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfaqplugin1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
