# Generated by Django 3.0.14 on 2022-06-01 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_centertext', serialize=False, to='cms.CMSPlugin')),
                ('full_text', djangocms_text_ckeditor.fields.HTMLField(help_text='Resumo completo do assunto', max_length=5000, verbose_name='Texto')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GenericPrivacyPolicyPlugin4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Política de Privacidade', max_length=100, verbose_name='Título')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(max_length=2000, verbose_name='Texto')),
                ('language', models.CharField(choices=[('pt-br', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol')], default='pt-br', max_length=5, verbose_name='Linguagem')),
            ],
            options={
                'verbose_name': 'Política de Privacidade',
                'verbose_name_plural': 'Políticas de Privacidade',
            },
        ),
        migrations.CreateModel(
            name='GenericTermsAndConditionsPlugin5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Termos e Condições', max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(default='', max_length=200, verbose_name='Subtítulo')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(max_length=2000, verbose_name='Texto')),
                ('language', models.CharField(choices=[('pt-br', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol')], default='pt-br', max_length=5, verbose_name='Linguagem')),
            ],
            options={
                'verbose_name': 'Termo e Condição',
                'verbose_name_plural': 'Termos e Condições',
            },
        ),
        migrations.CreateModel(
            name='ImagesResized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_mobile', models.ImageField(blank=True, help_text='Gerada Automáticamente.', max_length=400, upload_to='', verbose_name='Imagem mobile')),
                ('image_tablet', models.ImageField(blank=True, help_text='Gerada Automáticamente.', max_length=400, upload_to='', verbose_name='Imagem tablet')),
                ('image_desktop', models.ImageField(blank=True, help_text='Gerada Automáticamente.', max_length=400, upload_to='', verbose_name='Imagem desktop')),
                ('model_name', models.CharField(default='Model Name', max_length=150)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(default='Field Name', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LatestBlogPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_latestblogplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='Blog Tecnobeef', max_length=60)),
                ('label_show_all', models.CharField(default='Ver todos', help_text='Texto do botão "Ver todos"', max_length=60)),
                ('label_link_post', models.CharField(default='Leia no blog', help_text='Texto do link do blog "Leia no blog"', max_length=60)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='WeekPostsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_weekpostsplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='Destaque da semana', help_text='Texto do titulo do carrossel. Padrão: "Destaque da semana"', max_length=60)),
                ('label', models.CharField(default='continuar lendo', help_text='Texto do botão "Continue lendo"', max_length=60)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_youtubevideo', serialize=False, to='cms.CMSPlugin')),
                ('id_video', models.CharField(help_text='Insira a URL completa do vídeo', max_length=100, verbose_name='Link do Youtube')),
                ('describe_video', djangocms_text_ckeditor.fields.HTMLField(help_text='Descrição referente ao assunto do vídeo.', max_length=1000, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TextSideImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_textsideimage', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='Title notice', help_text='Titulo de referencia do assunto', max_length=50)),
                ('brief_text', djangocms_text_ckeditor.fields.HTMLField(help_text='Breve resumo do assunto', max_length=2500, verbose_name='Texto')),
                ('is_left_image', models.BooleanField(default=False, help_text='Escolha o lado da imagem (Padrão: direita)', verbose_name='Imagem na esquerda')),
                ('b2_side_image_size', models.CharField(default='620x355', editable=False, max_length=100)),
                ('text_alt', models.CharField(default='Imagem relacionada ao artigo', help_text='Digite o nome descritivo para a imagem.', max_length=120, verbose_name='Nome da imagem')),
                ('b2_side_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 620x355.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2_side_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Escolha uma imagem que mostrara ao lado dos textos')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageFullSizePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_imagefullsizeplugin', serialize=False, to='cms.CMSPlugin')),
                ('b1_background_image_size', models.CharField(default='1600x700', editable=False, max_length=100)),
                ('text_alt', models.CharField(default='Imagem relacionada ao artigo', help_text='Digite o nome descritivo para a imagem.', max_length=120, verbose_name='Nome da imagem')),
                ('b1_background_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 1600x700.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b1_background_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem de Fundo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GenericIconsPlugin3',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_genericiconsplugin3', serialize=False, to='cms.CMSPlugin')),
                ('g3_whatsapp_image_size', models.CharField(default='50x50', editable=False, max_length=100)),
                ('text_alt', models.CharField(default='Ícone do WhatsApp', help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('whatsapp_number', models.CharField(default='5517997929718', help_text='Inclua somente os números (ex: 5517999999999)', max_length=13, verbose_name='Número do Whatsapp')),
                ('g3_whatsapp_image_resize', filer.fields.image.FilerImageField(help_text='Tamanho ideal 50x50.', on_delete=django.db.models.deletion.PROTECT, related_name='g3_whats_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo do WhatsApp')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GenericHeaderPlugin1',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_genericheaderplugin1', serialize=False, to='cms.CMSPlugin')),
                ('g1_logo_image_size', models.CharField(default='205x26', editable=False, max_length=100)),
                ('text_alt', models.CharField(default='', help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('g1_logo_image_resize', filer.fields.image.FilerImageField(help_text='Tamanho ideal 205x26.', on_delete=django.db.models.deletion.PROTECT, related_name='g1_logo_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem da logo.')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GenericFooterPlugin2',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_genericfooterplugin2', serialize=False, to='cms.CMSPlugin')),
                ('g2_logo_image_size', models.CharField(default='158x20', editable=False, max_length=100)),
                ('text_alt', models.CharField(default='Logo da Tecnobeef', help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('url_instagram', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Link para o Instagram')),
                ('text_alt_instagram', models.CharField(default='', editable=False, help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('url_facebook', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Link para o Facebook')),
                ('text_alt_facebook', models.CharField(default='Ícone do Facebook', editable=False, help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('url_twitter', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Link para o Twitter')),
                ('text_alt_twitter', models.CharField(default='Ícone do Twitter', editable=False, help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('url_youtube', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Link do Youtube')),
                ('text_alt_youtube', models.CharField(default='Ícone do Youtube', editable=False, help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('url_linkedin', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Link do Linkedin')),
                ('text_alt_linkedin', models.CharField(default='Ícone do Linkedin', editable=False, help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem')),
                ('url_politica', models.CharField(blank=True, default='/genericapp/privacy/', editable=False, max_length=300, null=True, verbose_name='Link da Política de Privacidade ')),
                ('url_termos', models.CharField(blank=True, default='/genericapp/terms/', editable=False, max_length=300, null=True, verbose_name='Link dos Termos e Condições')),
                ('g2_logo_image_resize', filer.fields.image.FilerImageField(help_text='Tamanho ideal 158x20.', on_delete=django.db.models.deletion.PROTECT, related_name='g2_logo_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem da logo.')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DoubleImages',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genericapp_doubleimages', serialize=False, to='cms.CMSPlugin')),
                ('b2_first_image_size', models.CharField(default='610x350', editable=False, max_length=100)),
                ('first_text_alt', models.CharField(default='Imagem relacionada ao artigo', help_text='Digite o nome descritivo para a imagem.', max_length=120, verbose_name='Nome da imagem')),
                ('b2_second_image_size', models.CharField(default='610x350', editable=False, max_length=100)),
                ('second_text_alt', models.CharField(default='Imagem relacionada ao artigo', help_text='Digite o nome descritivo para a imagem.', max_length=120, verbose_name='Nome da imagem')),
                ('b2_first_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 610x350.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2_first_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Escolha uma imagem que mostrara na esquerda')),
                ('b2_second_image_resize', filer.fields.image.FilerImageField(blank=True, help_text='Tamanho ideal 610x350.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2_second_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Escolha uma imagem que mostrara na direita')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
