# Generated by Django 3.0.14 on 2022-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0002_auto_20220602_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='text_alt_linkedin',
        ),
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='text_alt_twitter',
        ),
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='url_linkedin',
        ),
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='url_politica',
        ),
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='url_termos',
        ),
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='url_twitter',
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='text_address',
            field=models.CharField(default='Estrada Municipal Linha Ávila, Rua Linha Carazal, 501 Gramado/RS - 95670-000', help_text='Digite o endereço com rua, numero, bairro e cep.', max_length=100, verbose_name='Endereço completo'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='text_alt_tiktok',
            field=models.CharField(default='Ícone do TikTok', editable=False, help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='text_email',
            field=models.CharField(default='acquamotion@gramadoparks.com', help_text='Digite o endereço de e-mail para contato.', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='text_hours',
            field=models.CharField(default='das 10h às 18h Consulte dias de abertura', help_text='Digite qual será o texto para indicar o horário de funcionamento. Ex.: Aberto das 09h ás 17h', max_length=100, verbose_name='Horário de funcionamento'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='text_phone',
            field=models.CharField(default='+55 54 3050-1700', help_text='Digite numero de telefone para contato.', max_length=100, verbose_name='Numero de telefone'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='title_newsletter',
            field=models.CharField(blank=True, default='Cadastre-se e receba promoções', editable=False, max_length=300, null=True, verbose_name='Texto do título da Newsletter'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='url_external',
            field=models.CharField(blank=True, default='https://www.gramadoparks.com.br/', max_length=300, null=True, verbose_name='Link de site externo'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='url_faq',
            field=models.CharField(blank=True, default='https://www.acquamotion.com.br/o-parque/informacoes/#informations-faq', editable=False, max_length=300, null=True, verbose_name='Link de perguntas frequentes'),
        ),
        migrations.AddField(
            model_name='genericfooterplugin2',
            name='url_tiktok',
            field=models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Link para o TikTok'),
        ),
        migrations.AddField(
            model_name='genericheaderplugin1',
            name='link_button',
            field=models.CharField(default='https://loja.multiclubes.com.br/acquamotion/ingressos/Loja Web', help_text='Coloque o link para onde será redirecionado. Ex.: https://loja.multiclubes.com.br/acquamotion/ingressos/Loja Web', max_length=100, verbose_name='Link do botão de pagamento'),
        ),
        migrations.AddField(
            model_name='genericheaderplugin1',
            name='link_menu',
            field=models.CharField(default='https://www.gramadoparks.com.br/', help_text='Coloque o link para onde será redirecionado. Ex.: https://www.gramadoparks.com.br/', max_length=50, verbose_name='Link do item no menu'),
        ),
        migrations.AddField(
            model_name='genericheaderplugin1',
            name='text_button',
            field=models.CharField(default='comprar ingressos', help_text='Digite um texto que exibira no botão de pagamento.', max_length=50, verbose_name='Texto do botão de pagamento'),
        ),
        migrations.AddField(
            model_name='genericheaderplugin1',
            name='text_menu',
            field=models.CharField(default='gramado parks', help_text='Digite um texto que exibira no item do menu', max_length=50, verbose_name='Texto do item no menu'),
        ),
        migrations.AlterField(
            model_name='genericfooterplugin2',
            name='text_alt',
            field=models.CharField(default='Logo do Acquamotion', help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem'),
        ),
        migrations.AlterField(
            model_name='genericfooterplugin2',
            name='text_alt_instagram',
            field=models.CharField(default='Ícone do Instagram', editable=False, help_text='Digite o nome descritivo para a imagem.', max_length=100, verbose_name='Nome da imagem'),
        ),
    ]
