# Generated by Django 3.0.14 on 2022-06-08 21:39

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0003_auto_20220608_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('termos', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.RemoveField(
            model_name='genericprivacypolicyplugin4',
            name='language',
        ),
        migrations.AlterField(
            model_name='genericfooterplugin2',
            name='text_address',
            field=djangocms_text_ckeditor.fields.HTMLField(default='Estrada Municipal Linha Ávila,<br>Rua Linha Carazal, 501<br>Gramado/RS - 95670-000', help_text='Digite o endereço com rua, numero, bairro e cep.', max_length=100, verbose_name='Endereço completo'),
        ),
        migrations.AlterField(
            model_name='genericfooterplugin2',
            name='text_hours',
            field=djangocms_text_ckeditor.fields.HTMLField(default='das 10h às 18h<br>Consulte dias de abertura', help_text='Digite qual será o texto para indicar o horário de funcionamento. Ex.: Aberto das 09h ás 17h', max_length=100, verbose_name='Horário de funcionamento'),
        ),
        migrations.AlterField(
            model_name='genericiconsplugin3',
            name='whatsapp_number',
            field=models.CharField(default='555430501700', help_text='Inclua somente os números (ex: 5517999999999)', max_length=13, verbose_name='Número do Whatsapp'),
        ),
    ]
