# Generated by Django 3.0.14 on 2022-06-14 15:54

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0005_auto_20220608_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericNoShowPlugin7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Política de Reagendamento, Cancelamento e No-Show', max_length=100, verbose_name='Título')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(max_length=2000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Política de Reagendamento, Cancelamento e No-Show',
                'verbose_name_plural': 'Política de Reagendamento, Cancelamento e No-Show',
            },
        ),
    ]
