# Generated by Django 3.0.14 on 2022-06-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('genericapp', '0006_genericnoshowplugin7'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Cadastro da Newsletter', 'verbose_name_plural': 'Cadastros das Newsletter'},
        ),
        migrations.AddField(
            model_name='genericheaderplugin1',
            name='g1_logo2_image_resize',
            field=filer.fields.image.FilerImageField(help_text='Tamanho ideal 205x26.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='g1_logo2_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem da logo secundária. Ex.: Logo Azul.'),
        ),
        migrations.AddField(
            model_name='genericheaderplugin1',
            name='g1_logo2_image_size',
            field=models.CharField(default='205x26', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='genericheaderplugin1',
            name='text_alt2',
            field=models.CharField(default='', help_text='Digite o nome descritivo para a imagem secundária.', max_length=100, verbose_name='Nome da imagem secundária'),
        ),
        migrations.AlterField(
            model_name='genericheaderplugin1',
            name='g1_logo_image_resize',
            field=filer.fields.image.FilerImageField(help_text='Tamanho ideal 205x26.', on_delete=django.db.models.deletion.PROTECT, related_name='g1_logo_image_resize', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem da logo Ex.: Logo Branca.'),
        ),
        migrations.AlterField(
            model_name='genericnoshowplugin7',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='genericnoshowplugin7',
            name='title',
            field=models.CharField(default='Política de Reagendamento, Cancelamento e No-Show', max_length=1000, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='genericprivacypolicyplugin4',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='generictermsandconditionsplugin5',
            name='subtitle',
            field=models.CharField(default='', max_length=5000, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='generictermsandconditionsplugin5',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='generictermsandconditionsplugin5',
            name='title',
            field=models.CharField(default='Termos e Condições', max_length=1000, verbose_name='Título'),
        ),
    ]
