# Generated by Django 3.0.14 on 2022-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0009_auto_20220825_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfooterplugin2',
            name='g2_logo_image_size',
            field=models.CharField(default='205x177', max_length=100),
        ),
        migrations.AlterField(
            model_name='genericheaderplugin1',
            name='g1_logo_image_size',
            field=models.CharField(default='205x177', max_length=100),
        ),
    ]
