# Generated by Django 3.0.14 on 2022-08-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0010_auto_20220825_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericheaderplugin1',
            name='g1_logo2_image_resize',
        ),
        migrations.RemoveField(
            model_name='genericheaderplugin1',
            name='g1_logo2_image_size',
        ),
        migrations.RemoveField(
            model_name='genericheaderplugin1',
            name='link_button',
        ),
        migrations.RemoveField(
            model_name='genericheaderplugin1',
            name='link_menu',
        ),
        migrations.RemoveField(
            model_name='genericheaderplugin1',
            name='text_alt2',
        ),
        migrations.RemoveField(
            model_name='genericheaderplugin1',
            name='text_button',
        ),
        migrations.RemoveField(
            model_name='genericheaderplugin1',
            name='text_menu',
        ),
    ]
