# Generated by Django 3.0.14 on 2022-08-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0012_auto_20220825_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='title_newsletter',
        ),
        migrations.RemoveField(
            model_name='genericfooterplugin2',
            name='url_external',
        ),
    ]
