# Generated by Django 3.0.14 on 2022-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0014_auto_20220825_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericiconsplugin3',
            name='whatsapp_number',
            field=models.CharField(default='5513997977005', help_text='Inclua somente os números (ex: 5517999999999)', max_length=13, verbose_name='Número do Whatsapp'),
        ),
    ]
