# Generated by Django 3.2.20 on 2023-09-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seometatags',
            options={'verbose_name': 'Google Corporation Meta Tag', 'verbose_name_plural': 'Google Corporation Meta Tags'},
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_address_locality',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_address_region',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_address_street',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_address_type',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_alterantive_name',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_description',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_logo',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_name',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_social_media_facebook',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_social_media_instagram',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_social_media_tiktok',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_social_media_youtube',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_telephone',
        ),
        migrations.RemoveField(
            model_name='seometatags',
            name='google_type',
        ),
        migrations.AlterField(
            model_name='seosinglepageplugin1',
            name='google_type',
            field=models.CharField(choices=[('Corporation', 'Corporação'), ('Organization', 'Organização'), ('product_list', 'Lista de Produtos'), ('product', 'Página de Produto')], default='Corporation', editable=False, max_length=12, verbose_name='Tipo de página'),
        ),
        migrations.CreateModel(
            name='GoogleProductMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_type', models.CharField(choices=[('Corporation', 'Corporação'), ('Organization', 'Organização'), ('product_list', 'Lista de Produtos'), ('product', 'Página de Produto')], default='product', editable=False, max_length=12, verbose_name='Tipo de página')),
                ('google_name', models.CharField(blank=True, default='Bela Marca', max_length=100, null=True, verbose_name='Nome do site')),
                ('google_alterantive_name', models.CharField(blank=True, default='Bela Marca: para mulheres poderosas como você.', max_length=200, null=True, verbose_name='Nome alternativo do site')),
                ('google_description', models.TextField(blank=True, default='Bela Marca: para mulheres poderosas como você.', max_length=500, null=True, verbose_name='Descrição do site')),
                ('google_logo', models.ImageField(default='../../static/assets/logo/logo_quadrado_turquesa.png', upload_to='seo_images/')),
                ('google_telephone', models.CharField(blank=True, default='5513997977005', max_length=20, null=True, verbose_name='Telefone para contato')),
                ('google_address_type', models.CharField(blank=True, default='postalAddress', editable=False, max_length=40, null=True, verbose_name='Tipo de endereço')),
                ('google_address_street', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Endereço')),
                ('google_address_locality', models.CharField(blank=True, default='Praia Grande', max_length=100, null=True, verbose_name='Cidade')),
                ('google_address_region', models.CharField(blank=True, default='SP', max_length=100, null=True, verbose_name='Estado')),
                ('google_social_media_facebook', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do Facebook')),
                ('google_social_media_instagram', models.URLField(blank=True, default='https://www.instagram.com/belamarcastore/', max_length=500, null=True, verbose_name='Link do Instagram')),
                ('google_social_media_youtube', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do Youtube')),
                ('google_social_media_tiktok', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do TikTok')),
                ('seo_meta_tags', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seoapp.seometatags')),
            ],
            options={
                'verbose_name': 'Google Product Meta Tag',
                'verbose_name_plural': 'Google Product Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='GoogleProductListMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_type', models.CharField(choices=[('Corporation', 'Corporação'), ('Organization', 'Organização'), ('product_list', 'Lista de Produtos'), ('product', 'Página de Produto')], default='product_list', editable=False, max_length=12, verbose_name='Tipo de página')),
                ('google_name', models.CharField(blank=True, default='Bela Marca', max_length=100, null=True, verbose_name='Nome do site')),
                ('google_alterantive_name', models.CharField(blank=True, default='Bela Marca: para mulheres poderosas como você.', max_length=200, null=True, verbose_name='Nome alternativo do site')),
                ('google_description', models.TextField(blank=True, default='Bela Marca: para mulheres poderosas como você.', max_length=500, null=True, verbose_name='Descrição do site')),
                ('google_logo', models.ImageField(default='../../static/assets/logo/logo_quadrado_turquesa.png', upload_to='seo_images/')),
                ('google_telephone', models.CharField(blank=True, default='5513997977005', max_length=20, null=True, verbose_name='Telefone para contato')),
                ('google_address_type', models.CharField(blank=True, default='postalAddress', editable=False, max_length=40, null=True, verbose_name='Tipo de endereço')),
                ('google_address_street', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Endereço')),
                ('google_address_locality', models.CharField(blank=True, default='Praia Grande', max_length=100, null=True, verbose_name='Cidade')),
                ('google_address_region', models.CharField(blank=True, default='SP', max_length=100, null=True, verbose_name='Estado')),
                ('google_social_media_facebook', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do Facebook')),
                ('google_social_media_instagram', models.URLField(blank=True, default='https://www.instagram.com/belamarcastore/', max_length=500, null=True, verbose_name='Link do Instagram')),
                ('google_social_media_youtube', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do Youtube')),
                ('google_social_media_tiktok', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do TikTok')),
                ('seo_meta_tags', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seoapp.seometatags')),
            ],
            options={
                'verbose_name': 'Google Product List Meta Tag',
                'verbose_name_plural': 'Google Product List Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='GoogleCorporationMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_type', models.CharField(choices=[('Corporation', 'Corporação'), ('Organization', 'Organização'), ('product_list', 'Lista de Produtos'), ('product', 'Página de Produto')], default='Corporation', editable=False, max_length=12, verbose_name='Tipo de página')),
                ('google_name', models.CharField(blank=True, default='Bela Marca', max_length=100, null=True, verbose_name='Nome do site')),
                ('google_alterantive_name', models.CharField(blank=True, default='Bela Marca: para mulheres poderosas como você.', max_length=200, null=True, verbose_name='Nome alternativo do site')),
                ('google_description', models.TextField(blank=True, default='Bela Marca: para mulheres poderosas como você.', max_length=500, null=True, verbose_name='Descrição do site')),
                ('google_logo', models.ImageField(default='../../static/assets/logo/logo_quadrado_turquesa.png', upload_to='seo_images/')),
                ('google_telephone', models.CharField(blank=True, default='5513997977005', max_length=20, null=True, verbose_name='Telefone para contato')),
                ('google_address_type', models.CharField(blank=True, default='postalAddress', editable=False, max_length=40, null=True, verbose_name='Tipo de endereço')),
                ('google_address_street', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Endereço')),
                ('google_address_locality', models.CharField(blank=True, default='Praia Grande', max_length=100, null=True, verbose_name='Cidade')),
                ('google_address_region', models.CharField(blank=True, default='SP', max_length=100, null=True, verbose_name='Estado')),
                ('google_social_media_facebook', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do Facebook')),
                ('google_social_media_instagram', models.URLField(blank=True, default='https://www.instagram.com/belamarcastore/', max_length=500, null=True, verbose_name='Link do Instagram')),
                ('google_social_media_youtube', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do Youtube')),
                ('google_social_media_tiktok', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Link do TikTok')),
                ('seo_meta_tags', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seoapp.seometatags')),
            ],
            options={
                'verbose_name': 'Google Corporation Meta Tag',
                'verbose_name_plural': 'Google Corporation Meta Tags',
            },
        ),
    ]
