# Generated by Django 3.2.20 on 2023-09-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0005_googlewebsitemetatag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seometatags',
            name='google_type',
        ),
    ]
