# Generated by Django 3.2.20 on 2023-09-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0007_auto_20230917_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleproductmetatag',
            name='google_product_price',
            field=models.CharField(blank=True, default='', help_text='Inserir somente o valor no seguinte formato "100.00".', max_length=12, null=True, verbose_name='Preço do Produto'),
        ),
    ]
