# Generated by Django 3.2.20 on 2023-09-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0008_alter_googleproductmetatag_google_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecorporationmetatag',
            name='google_alterantive_name',
            field=models.CharField(blank=True, default='Bela Marca - Beach Wear.', max_length=200, null=True, verbose_name='Nome alternativo do site'),
        ),
        migrations.AlterField(
            model_name='seometatags',
            name='title',
            field=models.CharField(blank=True, default='Bela Marca: para mulheres poderosas como você.', help_text='Dê a cada página um meta título exclusivo que reflita claramente o valor que a página carrega. Limite de 60 caracteres.', max_length=250, null=True, verbose_name='Título da página para SEO'),
        ),
    ]
